source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'NHBarScrollToolDemo' do

   pod 'NHExtension'
   pod 'NHBarScrollTool', :path=> '../NHBarScrollTool.podspec'
   pod 'MJRefresh'

end
