source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target 'NHBarScrollToolDemo' do

pod "MJRefresh"
pod 'NHBarScrollTool', :path=> '../NHBarScrollTool.podspec'
#pod 'NHExtension'
end
